import { apiRequest, toQueryString } from './apiClient';

export const adminDataService = {
  getInventory: async (includeDeleted = false, wing) => apiRequest(`/inventory/items${toQueryString({ includeDeleted, wing })}`),
  getParticipantCount: async ({ date, mealPeriod, itemId, wing }) => apiRequest(`/inventory/participant-count${toQueryString({ date, mealPeriod, itemId, wing })}`),
  createInventoryItem: async (payload) => apiRequest('/inventory/items', { method: 'POST', body: JSON.stringify(payload) }),
  updateInventoryItem: async (id, payload) => apiRequest(`/inventory/items/${id}`, { method: 'PUT', body: JSON.stringify(payload) }),
  deleteInventoryItem: async (id) => apiRequest(`/inventory/items/${id}`, { method: 'DELETE' }),
  forceDeleteInventoryItem: async (id) => apiRequest(`/inventory/items/${id}/force`, { method: 'DELETE' }),
  getInventoryLedger: async ({ itemId, from, to, wing }) => apiRequest(`/inventory/transactions${toQueryString({ itemId, from, to, wing })}`),
  createInventoryMovement: async (payload) => apiRequest('/inventory/transactions', { method: 'POST', body: JSON.stringify(payload) }),
  updateInventoryMovement: async (id, payload) => apiRequest(`/inventory/transactions/${id}`, { method: 'PUT', body: JSON.stringify(payload) }),
  deleteInventoryMovement: async (id) => apiRequest(`/inventory/transactions/${id}`, { method: 'DELETE' }),
  getAuditLogs: async () => apiRequest('/audit-logs'),
  getBillingRecords: async ({ month, year, gender = 'All', status = 'All' }) => apiRequest(`/billing/monthly${toQueryString({ month, year, gender, status })}`),
  createDswSubsidy: async (payload) => apiRequest('/billing/subsidies', { method: 'POST', body: JSON.stringify(payload) }),
  getDswSubsidies: async ({ month, year, wing }) => apiRequest(`/billing/subsidies${toQueryString({ month, year, wing })}`),
  updateDswSubsidy: async (id, payload) => apiRequest(`/billing/subsidies/${id}`, { method: 'PUT', body: JSON.stringify(payload) }),
  deleteDswSubsidy: async (id) => apiRequest(`/billing/subsidies/${id}`, { method: 'DELETE' }),
  getServiceBill: async ({ month, year }) => apiRequest(`/billing/service-bills${toQueryString({ month, year })}`),
  deleteServiceBill: async ({ month, year }) => apiRequest(`/billing/service-bills${toQueryString({ month, year })}`, { method: 'DELETE' }),
  recalculateBillingMonth: async ({ month, year }) => apiRequest(`/billing/subsidies/recalculate${toQueryString({ month, year })}`, { method: 'POST' }),
  saveServiceBill: async (payload) => apiRequest('/billing/service-bills', { method: 'PUT', body: JSON.stringify(payload) }),
  closeBillingPeriod: async (payload) => apiRequest('/billing/periods/close', { method: 'POST', body: JSON.stringify(payload) }),
  unlockBillingPeriod: async (payload) => apiRequest('/billing/periods/unlock', { method: 'POST', body: JSON.stringify(payload) }),
  getPayments: async (gender) => apiRequest(`/payments/admin${toQueryString({ gender })}`),
  reviewPayment: async (id, action, approvedAmount = null) => apiRequest(`/payments/${id}/review`, {
    method: 'POST',
    body: JSON.stringify({ action, approvedAmount }),
  }),
  getDueRows: async (month, year, gender) => apiRequest(`/due${toQueryString({ month, year, gender })}`),
  saveDueAdjustment: async (payload) => apiRequest('/due/adjustments', { method: 'POST', body: JSON.stringify(payload) }),
  getDailyCost: async (month, year, gender) => apiRequest(`/daily-cost${toQueryString({ month, year, gender })}`),
  searchStudents: async (q, wing) => apiRequest(`/admin/students/search${toQueryString({ q, wing })}`),
  getMealModule: async (wing) => apiRequest(`/meals/module${toQueryString({ wing })}`),
  getMealCounts: async (date, wing) => apiRequest(`/meals/counts${toQueryString({ date, wing })}`),
  // Global meal overrides
  getGlobalOverrides: async (from, to, wing) => apiRequest(`/meals/overrides${toQueryString({ from, to, wing })}`),
  createGlobalOverride: async (payload) => apiRequest('/meals/overrides', { method: 'POST', body: JSON.stringify(payload) }),
  deleteGlobalOverride: async (id) => apiRequest(`/meals/overrides/${id}`, { method: 'DELETE' }),
  getStudentMealControl: async (studentRecordId, date, wing) => apiRequest(`/meals/student-controls/${studentRecordId}${toQueryString({ date, wing })}`),
  saveStudentMealControlStatus: async (payload) => apiRequest('/meals/student-controls/status', { method: 'PUT', body: JSON.stringify(payload) }),
  getMealSheet: async (date, wing) => apiRequest(`/meals/sheet${toQueryString({ date, wing })}`),
  getAdminAccounts: async () => apiRequest('/admin-settings/admins'),
  createAdminAccount: async (payload) => apiRequest('/admin-settings/admins', { method: 'POST', body: JSON.stringify(payload) }),
  updateAdminAccount: async (id, payload) => apiRequest(`/admin-settings/admins/${id}`, { method: 'PUT', body: JSON.stringify(payload) }),
};
